# Site
repository: Narayan/my-resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Vishnu Narayan Rai
title: Backend Developer
email: vishnunarayan1670@gmail.com
website: https://leetcode.com/VishnuRai/

# Dark Mode (true/false/never)
darkmode: true

# Social links

github_username:  Narayan1670

linkedin_username: vishnu-rai-765412192


# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Vishnu and I'm an upcoing Assosiate Software Engineer at Accenture. I like developing Backend applications with Javascript. I also like solving DSA problems with Java.

  I am most skilled in: <mark>NodeJS</mark> , <mark>MongoDB</mark>, <mark>MySQL</mark> , <mark>Express</mark> , <mark>Redis</mark> and <mark>React(Basic)</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Decentralised ChatRoom
        link: https://decentralised-app-6f930.web.app/
        # link_text: 
        additional_links:
          - title:  Narayan1670/Decentralised-Chatroom
            icon: fab fa-github
            url: https://github.com/Narayan1670/Decentralised-Chatroom
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A decentralized chat app built with GUN.js and Svelte
        description: | # this will include new lines to allow paragraphs
          This is an Serverless Chatroom App. I started this project as a way if learning <mark>NodeJS</mark> and it has Frontend as Svelte and Backend with gun.js which is decentralized database. It is hosted live with the help of firebase.

  

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: JSSATE, Noida
        caption: 2019 - 2022
        sub_title: B.tech E&C
       # quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Jss I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a  member of the *Slum Swaraj Foundation* which provide eduction to the unpreviliged children.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - calisthenics
      - Gaming
      - Cooking

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
